id: P003086
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG22089
  title: ཁྲེགས་ཆོད་ཀྱི་ཁྲིད་གསེར་གྱི་ཐེམ་སྐས།
  author: ''
  volumes:
    43778f7c81c84fdc8467c2251737ff4b:
      image_group_id: I1KG22136
      title: ''
      volume_number: 1
      total_pages: 92
      base_file: v001.txt
