id: I43690496
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:36:12+00:00'
last_modified: '2022-06-07T17:27:59.134361+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22089
  title: ཁྲེགས་ཆོད་ཀྱི་ཁྲིད་གསེར་གྱི་ཐེམ་སྐས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BFB1:
      image_group_id: I1KG22136
      title: ''
      total_pages: 92
      order: 1
      base_file: BFB1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
